apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bxm63d8no-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:cb8c28eb1fdd07654bfe31486cd49935d1d5162f@sha256:0c09128b0b646b3dbe0ea616632e956619a9d6a4dc6bae2495953a23f1e0c1f5
          name: container-image
